#! /bin/sh
# Author: Rahul Jain . rajain

# Akamai aliases
alias sshlocalvm='ssh guest@192.168.56.101'
alias sshlsge='ssh -i ~/.ssh/external/rajain-deployed-2013-08-07 rajain@lsg-east.akamai.com'
alias sshlsgw='ssh -i ~/.ssh/external/rajain-deployed-2013-08-07 rajain@lsg-west.akamai.com'
alias gwshETN1='gwsh -2 -i ~/.ssh/external/rajain-deployed-2013-08-07 root@205.185.220.220'
alias gwshETN7='gwsh -2 -i ~/.ssh/external/rajain-deployed-2013-08-07 root@205.185.220.230'

# Usage: gwshESN ESN_IP-Address
# Example: gwshESN 69.31.17.134
function gwshESN()
{
   gwsh -2 -i ~/.ssh/external/rajain-deployed-2013-08-07 testgrp@$1;
}

# Akamai curl
# Usage example: akacurl www.target.com http://www.target.com
akacurl ()
{
   #unless specified, User-Agent is assumed to be Google Chrome.
   userAgentExists=false
   for arg in $@ ; do
      if [ $arg == '-A' ] ; then
         userAgentExists=true
         break
      fi
   done
   if $userAgentExists ; then
      curl -s -D - -o /dev/null -L -H "Pragma: akamai-x-cache-on, akamai-x-get-cache-key, akamai-x-get-true-cache-key, akamai-x-cache-remote-on, akamai-x-check-cacheable, akamai-x-get-extracted-values, akamai-x-get-nonces, akamai-x-get-ssl-client-session-id, akamai-x-get-true-cache-key, x-rate-limiting-data, akamai-x-get-request-id, akamai-x-serial-no, X-Akamai-Meta-Trace: 1" -H "Host: $1" "${@:2}"
   else
      curl -s -D - -o /dev/null -L -H "Pragma: akamai-x-cache-on, akamai-x-get-cache-key, akamai-x-get-true-cache-key, akamai-x-cache-remote-on, akamai-x-check-cacheable, akamai-x-get-extracted-values, akamai-x-get-nonces, akamai-x-get-ssl-client-session-id, akamai-x-get-true-cache-key, x-rate-limiting-data, akamai-x-get-request-id, akamai-x-serial-no, X-Akamai-Meta-Trace: 1" -H "Host: $1" "${@:2}" -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36"
   fi
}

# Usage example: akarepeatcurl 10 www.target.com http://www.target.com/Home
akarepeatcurl ()
{
   for n in {1..$1} ; do
      akacurl $2 ${@:3}
   done
}

# Usage: akalistcurl hostName fileName
# Example: akalistcurl www.target.com urlList.txt
# All URLs in the file should be for the same host.
# Delimiter is \n. So the last line should have \n after it, ie, 
# there should be a blank line at the end.
akalistcurl ()
{
   while read line
   do
      echo $line
      akacurl $1 $line ;
      wait
      echo "\n\n======================\n\n"
   done < $2
}

# Generate PPK pair for Akamai NetStorage
# Usage: akanskeygen localDirName
akanskeygen ()
{
   if [ ! -d ~/Documents/Akamai/Akamai_sshKeys/NetStorageKeys/$1 ] ; then
      mkdir -p ~/Documents/Akamai/Akamai_sshKeys/NetStorageKeys/$1
   fi

   ssh-keygen -v -t rsa -b 2048 -C "$1-rajain-$(date +%Y-%m-%d)" -f ~/Documents/Akamai/Akamai_sshKeys/NetStorageKeys/$1/$1-rajain-$(date +%Y-%m-%d)
}

# sftp to Akamai NetStorage
# Usage: akanssftp localDirName netstorageAccountName up/down
akanssftp ()
{
   keyfiledir=~/Documents/Akamai/Akamai_sshKeys/NetStorageKeys/$1
   if [ ! -d $keyfiledir ] ; then
      echo "No such directory: $keyfiledir"
      return 1
   fi
   privatekey=$(ls $keyfiledir | grep -iv "pub")
   sftp -i $keyfiledir/$privatekey sshacs@$2.$3load.akamai.com
}


#echo | nsh 216.246.75.19 s_client --ssl3 origin-m-dt-web-c1.jcpenney.com 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | openssl x509 -noout -enddate 
