use FanFueled

insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookLikeBaseTripRecords', 1, 30)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookLikeAviator', 2, 10)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookLikeGreyScale', 4, 10)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookLikeLespecial', 8, 10)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookLikeMicahRaps', 16, 10)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookLikeMoePopeMusic', 32, 10)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookLikeRaja', 64, 10)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookLikeStephBarrak', 128, 10)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookLikeSupersillyus', 256, 10)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookLikeWobblesauce', 512, 10)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookLikeBrainChildMedia', 1024, 10)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookLikeFF', 2048, 10)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookLikeBrainTrust', 4096, 30)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'Census', 8192, 50)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookWallPostLiveEvent', 16384, 30)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookFriendPost', 32768, 30)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'Tweet', 65536, 30)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'TwitterFollowBrainTrust', 131072, 10)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'TwitterFollowFF', 262144, 5)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'TwitterFollowBaseTripRecords', 524288, 10)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookWallPostFavMusicVenue', 1048576, 25)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookWallPostNewYearResolution', 2097152, 30)
insert into BadgeAction (BadgeID, ActionName, ActionValue, ActionPoints) values (4, 'FacebookWallPostFavBrainTrustArtist', 4194304, 20)

select * from BadgeAction where BadgeID=4
