select * from EN_Reward where ProgramID=2

insert into EN_RewardImage (RewardID, Path, IsPrimary) values 
(1, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_25_perc_off.jpg', 1),
(1, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_25_perc_off.jpg', 1),
(2, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_wobble_monthpass.jpg', 1),
(2, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_wobble_monthpass.jpg', 1),
(3, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_50_perc_off.jpg', 1),
(3, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_50_perc_off.jpg', 1),
(4, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_any_album_from_catalog.jpg', 1),
(4, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_any_album_from_catalog.jpg', 1),
(5, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_gardo_showprint.jpg', 1),
(5, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_gardo_showprint.jpg', 1),
(6, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_1_ticket_bt_show.jpg', 1),
(6, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_1_ticket_bt_show.jpg', 1),
(7, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_braintrust_tee.jpg', 1),
(7, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_braintrust_tee.jpg', 1),
(8, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_wobble_monthpass.jpg', 1),
(8, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_wobble_monthpass.jpg', 1),
(9, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_2_tickets_bt_show.jpg', 1),
(9, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_2_tickets_bt_show.jpg', 1),
(10, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_signed_bt_artist_album.jpg', 1),
(10, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_signed_bt_artist_album.jpg', 1),
(11, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_gardo_signed_showprint.jpg', 1),
(11, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_gardo_signed_showprint.jpg', 1),
(12, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_artist_meetgreet.jpg', 1),
(12, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_artist_meetgreet.jpg', 1),
(13, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_brainiac_package.jpg', 1),
(13, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_brainiac_package.jpg', 1),
(14, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_wobble_vip_bottleservice.jpg', 1),
(14, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_wobble_vip_bottleservice.jpg', 1),
(15, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_einstein_package.jpg', 1),
(15, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_einstein_package.jpg', 1),
(16, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Large_braintrust_package.jpg', 1),
(16, 'https://s3.amazonaws.com/fanfueled-engage/images/brain-trust-images/briantrust-prizesBraintrust_Med_braintrust_package.jpg', 1)